on: push

jobs:
  connected-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run connected tests
        run: ./gradlew connectedCheck
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: